# This workflow will perform code review on a Java project with Gradle

name: Java Code Review

on: [push]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "oracle"

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # Update permission for gradle wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Runs check. Imported by checkstyle plugin. This will
      # check for google java code style
      # perform static code analysis
      - name: Run check
        run: ./gradlew check

      # Runs javadoc
      - name: Run javadoc
        run: ./gradlew javadoc
